platform :ios,'5.0'
pod 'JASidePanels'
pod 'ASIHTTPRequest'
pod 'MBProgressHUD'
pod 'EGOTableViewPullRefresh'
#pod 'LoadMoreTableFooterView', :git => 'https://github.com/sishen/LoadMoreTableFooterView.git'
pod 'CocoaLumberjack'