platform :ios,'6.1'
pod 'JASidePanels'
pod 'ASIHTTPRequest'
pod 'MBProgressHUD'
#pod 'EGOTableViewPullRefresh'
#pod 'LoadMoreTableFooterView', :git => 'https://github.com/sishen/LoadMoreTableFooterView.git'
pod 'CocoaLumberjack'
pod 'SVProgressHUD'
#pod 'ViewDeck','~> 2.2.11'
pod 'RTLabel'
pod 'KxMenu'
pod 'DAContextMenuTableViewController'
pod 'SWTableViewCell'
#pod 'RMSwipeTableViewCell'
pod 'HMSegmentedControl', '~> 1.3.0'
pod 'REMenu', '~> 1.7.1'
pod 'Harpy'